<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Common\**" />
    <Compile Remove="Enum\**" />
    <Compile Remove="Identity\**" />
    <EmbeddedResource Remove="Common\**" />
    <EmbeddedResource Remove="Enum\**" />
    <EmbeddedResource Remove="Identity\**" />
    <None Remove="Common\**" />
    <None Remove="Enum\**" />
    <None Remove="Identity\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.5" />
  </ItemGroup>

</Project>
