<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TeamIndia.TalentFlow.Application\TeamIndia.TalentFlow.Application.csproj" />
		<ProjectReference Include="..\TeamIndia.TalentFlow.Infrastructure\TeamIndia.TalentFlow.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Configurations\" />
		<Folder Include="Configurations\" />
		<Folder Include="Configurations\" />
		<Folder Include="Models\" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Resources\Emails\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\certificate_design.html">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>
